name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  Build:
    uses: microsoft/digitalworkplace-workflows/.github/workflows/build.yml@v2.0
    with:
     project-to-build: "src/Generator/Generator.csproj"
     project-to-test: "test/Generator.Tests/Generator.Tests.csproj"
     coverage-threshold: 89

  Pack:
    uses: microsoft/digitalworkplace-workflows/.github/workflows/pack.yml@v2.0
    with:
      project-to-pack: "src/Generator/Generator.csproj"